name: booking-order-app # change this to your app name
services:
  user-service: # change this to your service name
    container_name: user-service # change this to your service name
    # image: ykrambe/user-service:1 # change this to your image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001' # change this to your port
    env_file:
      - .env
